import { ApkScanResult } from '../types';

export const SAMPLE_APKS: ApkScanResult[] = [
  {
    appName: 'Đèn Pin Pro (Flashlight LED)',
    packageName: 'com.brighttorch.flashlight.pro',
    version: '2.5.1',
    fileSizeMb: 3.2,
    scanTime: '26/09/2026 - 10:14:22',
    appCategory: 'flashlight',
    categoryNameVi: 'Đèn pin (Flashlight)',
    totalPermissions: 8,
    dangerousCount: 4,
    violationCount: 3,
    complianceScore: 35,
    complianceRating: 'RED',
    ratingLabel: 'VI PHẠM NGHIÊM TRỌNG',
    violationsSummary: [
      'Vi phạm Quy tắc 3 (GDPR & Luật BV Dữ Liệu Cá Nhân 2025): Tối thiểu hóa dữ liệu (Data Minimization) - Thu thập danh bạ và tin nhắn ngoài phạm vi chức năng',
      'Vi phạm Quy tắc 2: Mục đích giới hạn - Không có căn cứ xác thực đòi hỏi vị trí GPS cho công cụ đèn pin',
    ],
    recommendations: [
      'Loại bỏ ngay quyền android.permission.READ_CONTACTS trong AndroidManifest.xml',
      'Loại bỏ ngay quyền android.permission.READ_SMS vì ứng dụng không có tính năng SMS',
      'Loại bỏ quyền android.permission.ACCESS_FINE_LOCATION để tránh vi phạm theo dõi người dùng',
      'Chỉ giữ lại CAMERA / FLASHLIGHT và WAKE_LOCK để duy trì chức năng cốt lõi',
    ],
    permissions: [
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Cần để kích hoạt và điều khiển đèn flash LED máy ảnh',
        description: 'Truy cập máy ảnh để bật đèn flash',
      },
      {
        name: 'android.permission.READ_CONTACTS',
        shortName: 'READ_CONTACTS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - App đèn pin không có bất kỳ nhu cầu nào truy cập danh bạ người dùng!',
        ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu (Data Minimization)',
        description: 'Đọc toàn bộ danh bạ điện thoại',
      },
      {
        name: 'android.permission.READ_SMS',
        shortName: 'READ_SMS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm nghiêm trọng - Đọc mã OTP và tin nhắn riêng tư, nguy cơ rò rỉ dữ liệu tài chính!',
        ruleViolated: 'Quy tắc 3 & Quy tắc 5: Tối thiểu hóa & Bảo mật an toàn',
        description: 'Đọc tin nhắn SMS và OTP',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - App đèn pin không cần tọa độ vị trí GPS chính xác của người dùng!',
        ruleViolated: 'Quy tắc 2: Mục đích giới hạn (Purpose Limitation)',
        description: 'Định vị GPS chính xác vị trí người dùng',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Tải banner quảng cáo hoặc kiểm tra cập nhật phiên bản',
        description: 'Kết nối mạng Internet',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Kiểm tra trạng thái kết nối Wi-Fi/4G',
        description: 'Kiểm tra trạng thái mạng',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Rung xúc giác (haptic feedback) khi nhấn nút On/Off',
        description: 'Điều khiển rung thiết bị',
      },
      {
        name: 'android.permission.WAKE_LOCK',
        shortName: 'WAKE_LOCK',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Giữ màn hình và đèn sáng liên tục không bị tắt',
        description: 'Ngăn máy tự khóa màn hình khi đang bật đèn',
      },
    ],
  },
  {
    appName: 'Máy Tính Bỏ Túi Tiện Lợi (Simple Calc)',
    packageName: 'org.cleanapp.calculator',
    version: '1.0.4',
    fileSizeMb: 1.8,
    scanTime: '26/09/2026 - 11:05:10',
    appCategory: 'calculator',
    categoryNameVi: 'Máy tính bỏ túi (Calculator)',
    totalPermissions: 3,
    dangerousCount: 0,
    violationCount: 0,
    complianceScore: 95,
    complianceRating: 'GREEN',
    ratingLabel: 'TUÂN THỦ RẤT TỐT',
    violationsSummary: [],
    recommendations: [
      'Ứng dụng tuân thủ rất tốt nguyên tắc Tối thiểu hóa dữ liệu (GDPR & Luật Việt Nam 2025).',
      'Không yêu cầu bất kỳ quyền nhạy cảm (Dangerous permissions) nào.',
    ],
    permissions: [
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Phản hồi rung nhẹ khi bấm các phím số và dấu tính',
        description: 'Rung phản hồi bàn phím',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Tỷ giá tiền tệ trực tuyến và chuyển đổi đơn vị',
        description: 'Truy cập mạng để cập nhật tỷ giá',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Nhận biết khi thiết bị offline để dùng bộ nhớ đệm',
        description: 'Kiểm tra kết nối mạng',
      },
    ],
  },
  {
    appName: 'Mạng Xã Hội Connect Chat',
    packageName: 'vn.social.connect.chat',
    version: '3.2.0',
    fileSizeMb: 42.5,
    scanTime: '26/09/2026 - 09:40:15',
    appCategory: 'social_media',
    categoryNameVi: 'Mạng xã hội & Chat (Social Media)',
    totalPermissions: 9,
    dangerousCount: 6,
    violationCount: 2,
    complianceScore: 62,
    complianceRating: 'YELLOW',
    ratingLabel: 'CẢNH BÁO TUÂN THỦ',
    violationsSummary: [
      'Yêu cầu quyền truy cập SMS trong khi ứng dụng đã dùng xác thực OTP qua Email hoặc Push Notification',
      'Định vị ngầm liên tục (ACCESS_BACKGROUND_LOCATION) không cần thiết cho ứng dụng mạng xã hội thông thường',
    ],
    recommendations: [
      'Thay thế READ_SMS bằng SMS Retriever API của Google để nhận OTP an toàn không cần đọc hòm thư',
      'Hạ cấp từ ACCESS_BACKGROUND_LOCATION xuống ACCESS_COARSE_LOCATION chỉ khi người dùng chủ động check-in',
    ],
    permissions: [
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Chụp ảnh avatar và gửi story hoặc video call',
        description: 'Chụp ảnh và gọi video call',
      },
      {
        name: 'android.permission.RECORD_AUDIO',
        shortName: 'RECORD_AUDIO',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Ghi âm tin nhắn thoại và đàm thoại âm thanh',
        description: 'Ghi âm tin nhắn thoại',
      },
      {
        name: 'android.permission.READ_CONTACTS',
        shortName: 'READ_CONTACTS',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý có điều kiện - Tìm kiếm bạn bè từ danh bạ (cần sự đồng ý rõ ràng)',
        description: 'Đồng bộ hóa danh bạ tìm bạn bè',
      },
      {
        name: 'android.permission.READ_SMS',
        shortName: 'READ_SMS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Không nên xin toàn quyền đọc SMS người dùng chỉ để lấy mã OTP',
        ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu',
        description: 'Đọc hòm thư tin nhắn SMS',
      },
      {
        name: 'android.permission.ACCESS_BACKGROUND_LOCATION',
        shortName: 'ACCESS_BACKGROUND_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Theo dõi vị trí ngầm 24/7 xâm phạm đời tư người dùng nghiêm trọng',
        ruleViolated: 'Quy tắc 1 & 3: Thiếu căn cứ hợp pháp và xâm phạm quyền riêng tư',
        description: 'Định vị ngầm chạy liên tục',
      },
      {
        name: 'android.permission.READ_MEDIA_IMAGES',
        shortName: 'READ_MEDIA_IMAGES',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Cho phép người dùng chọn ảnh tải lên bài viết',
        description: 'Đọc thư viện ảnh',
      },
      {
        name: 'android.permission.POST_NOTIFICATIONS',
        shortName: 'POST_NOTIFICATIONS',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Báo tin nhắn mới và thông báo hoạt động bạn bè',
        description: 'Gửi thông báo tin nhắn',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Kết nối máy chủ truyền dữ liệu chat',
        description: 'Kết nối mạng',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Quản lý trạng thái mạng',
        description: 'Kiểm tra trạng thái mạng',
      },
    ],
  },
  {
    appName: 'Beauty Filter Photo Editor',
    packageName: 'com.filter.beautycam.art',
    version: '4.0.1',
    fileSizeMb: 28.4,
    scanTime: '26/09/2026 - 08:22:04',
    appCategory: 'photo_editor',
    categoryNameVi: 'Chỉnh sửa ảnh / Camera (Photo Editor)',
    totalPermissions: 6,
    dangerousCount: 4,
    violationCount: 2,
    complianceScore: 55,
    complianceRating: 'YELLOW',
    ratingLabel: 'CẢNH BÁO TUÂN THỦ',
    violationsSummary: [
      'App chỉnh sửa ảnh xin quyền đọc số điện thoại và trạng thái cuộc gọi (READ_PHONE_STATE)',
      'Thu thập tọa độ vị trí chính xác người dùng (ACCESS_FINE_LOCATION) không phục vụ tính năng lọc ảnh',
    ],
    recommendations: [
      'Loại bỏ quyền android.permission.READ_PHONE_STATE',
      'Loại bỏ quyền android.permission.ACCESS_FINE_LOCATION, nếu cần gắn geotag vào ảnh hãy hỏi xin riêng biệt',
    ],
    permissions: [
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Chụp ảnh trực tiếp với filter làm đẹp',
        description: 'Máy ảnh chụp hình',
      },
      {
        name: 'android.permission.READ_EXTERNAL_STORAGE',
        shortName: 'READ_EXTERNAL_STORAGE',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Mở ảnh từ album để chỉnh sửa',
        description: 'Đọc ảnh từ bộ nhớ',
      },
      {
        name: 'android.permission.READ_PHONE_STATE',
        shortName: 'READ_PHONE_STATE',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Ứng dụng lọc ảnh không có lý do chính đáng để đọc IMEI và số thuê bao!',
        ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu cá nhân',
        description: 'Đọc số điện thoại & IMEI máy',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Định vị người dùng khi đang áp dụng filter không có cơ sở pháp lý',
        ruleViolated: 'Quy tắc 2: Mục đích giới hạn',
        description: 'Lấy vị trí GPS người dùng',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Tải gói sticker và bộ lọc màu mới từ cloud',
        description: 'Kết nối mạng',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Rung nhẹ khi chụp xong ảnh',
        description: 'Rung máy',
      },
    ],
  },
];
