import { ApkScanResult } from '../types';

export const SAMPLE_APKS: ApkScanResult[] = [
  {
    appName: 'Đèn Pin Pro (Flashlight LED)',
    packageName: 'com.brighttorch.flashlight.pro',
    version: '2.5.1',
    fileSizeMb: 3.2,
    scanTime: '26/09/2026 - 10:14:22',
    appCategory: 'flashlight',
    categoryNameVi: 'Đèn pin (Flashlight)',
    totalPermissions: 8,
    dangerousCount: 4,
    violationCount: 3,
    complianceScore: 1,
    complianceRating: 'RED',
    ratingLabel: 'VI PHẠM NGHIÊM TRỌNG (RED)',
    violationsSummary: [
      'Vi phạm Quy tắc 3 (GDPR & Luật BV Dữ Liệu Cá Nhân 2025): Tối thiểu hóa dữ liệu (Data Minimization) - Thu thập danh bạ và tin nhắn ngoài phạm vi chức năng',
      'Vi phạm Quy tắc 2: Mục đích giới hạn - Không có căn cứ xác thực đòi hỏi vị trí GPS cho công cụ đèn pin',
    ],
    recommendations: [
      'Loại bỏ ngay quyền android.permission.READ_CONTACTS trong AndroidManifest.xml',
      'Loại bỏ ngay quyền android.permission.READ_SMS vì ứng dụng không có tính năng SMS',
      'Loại bỏ quyền android.permission.ACCESS_FINE_LOCATION để tránh vi phạm theo dõi người dùng',
      'Chỉ giữ lại CAMERA / FLASHLIGHT và WAKE_LOCK để duy trì chức năng cốt lõi',
    ],
    permissions: [
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Cần để kích hoạt và điều khiển đèn flash LED máy ảnh',
        description: 'Truy cập máy ảnh để bật đèn flash',
      },
      {
        name: 'android.permission.READ_CONTACTS',
        shortName: 'READ_CONTACTS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - App đèn pin không có bất kỳ nhu cầu nào truy cập danh bạ người dùng!',
        ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu (Data Minimization)',
        description: 'Đọc toàn bộ danh bạ điện thoại',
      },
      {
        name: 'android.permission.READ_SMS',
        shortName: 'READ_SMS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm nghiêm trọng - Đọc mã OTP và tin nhắn riêng tư, nguy cơ rò rỉ dữ liệu tài chính!',
        ruleViolated: 'Quy tắc 3 & Quy tắc 5: Tối thiểu hóa & Bảo mật an toàn',
        description: 'Đọc tin nhắn SMS và OTP',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - App đèn pin không cần tọa độ vị trí GPS chính xác của người dùng!',
        ruleViolated: 'Quy tắc 2: Mục đích giới hạn (Purpose Limitation)',
        description: 'Định vị GPS chính xác vị trí người dùng',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Tải banner quảng cáo hoặc kiểm tra cập nhật phiên bản',
        description: 'Kết nối mạng Internet',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Kiểm tra trạng thái kết nối Wi-Fi/4G',
        description: 'Kiểm tra trạng thái mạng',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Rung xúc giác (haptic feedback) khi nhấn nút On/Off',
        description: 'Điều khiển rung thiết bị',
      },
      {
        name: 'android.permission.WAKE_LOCK',
        shortName: 'WAKE_LOCK',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Giữ màn hình và đèn sáng liên tục không bị tắt',
        description: 'Ngăn máy tự khóa màn hình khi đang bật đèn',
      },
    ],
  },
  {
    appName: 'Máy Tính Bỏ Túi Tiện Lợi (Simple Calc)',
    packageName: 'org.cleanapp.calculator',
    version: '1.0.4',
    fileSizeMb: 1.8,
    scanTime: '26/09/2026 - 11:05:10',
    appCategory: 'calculator',
    categoryNameVi: 'Máy tính bỏ túi (Calculator)',
    totalPermissions: 3,
    dangerousCount: 0,
    violationCount: 0,
    complianceScore: 100,
    complianceRating: 'GREEN',
    ratingLabel: 'TUÂN THỦ RẤT TỐT (GREEN)',
    violationsSummary: [],
    recommendations: [
      'Ứng dụng tuân thủ rất tốt nguyên tắc Tối thiểu hóa dữ liệu (GDPR & Luật Việt Nam 2025).',
      'Không yêu cầu bất kỳ quyền nhạy cảm (Dangerous permissions) nào.',
    ],
    permissions: [
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Phản hồi rung nhẹ khi bấm các phím số và dấu tính',
        description: 'Rung phản hồi bàn phím',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Tỷ giá tiền tệ trực tuyến và chuyển đổi đơn vị',
        description: 'Truy cập mạng để cập nhật tỷ giá',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Nhận biết khi thiết bị offline để dùng bộ nhớ đệm',
        description: 'Kiểm tra kết nối mạng',
      },
    ],
  },
  {
    appName: 'Mạng Xã Hội Connect Chat',
    packageName: 'vn.social.connect.chat',
    version: '3.2.0',
    fileSizeMb: 42.5,
    scanTime: '26/09/2026 - 09:40:15',
    appCategory: 'social_media',
    categoryNameVi: 'Mạng xã hội & Chat (Social Media)',
    totalPermissions: 9,
    dangerousCount: 6,
    violationCount: 2,
    complianceScore: 42,
    complianceRating: 'RED',
    ratingLabel: 'VI PHẠM NGHIÊM TRỌNG (RED)',
    violationsSummary: [
      'Yêu cầu quyền truy cập SMS trong khi ứng dụng đã dùng xác thực OTP qua Email hoặc Push Notification',
      'Định vị ngầm liên tục (ACCESS_BACKGROUND_LOCATION) không cần thiết cho ứng dụng mạng xã hội thông thường',
    ],
    recommendations: [
      'Thay thế READ_SMS bằng SMS Retriever API của Google để nhận OTP an toàn không cần đọc hòm thư',
      'Hạ cấp từ ACCESS_BACKGROUND_LOCATION xuống ACCESS_COARSE_LOCATION chỉ khi người dùng chủ động check-in',
    ],
    permissions: [
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Chụp ảnh avatar và gửi story hoặc video call',
        description: 'Chụp ảnh và gọi video call',
      },
      {
        name: 'android.permission.RECORD_AUDIO',
        shortName: 'RECORD_AUDIO',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Ghi âm tin nhắn thoại và đàm thoại âm thanh',
        description: 'Ghi âm tin nhắn thoại',
      },
      {
        name: 'android.permission.READ_CONTACTS',
        shortName: 'READ_CONTACTS',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý có điều kiện - Tìm kiếm bạn bè từ danh bạ (cần sự đồng ý rõ ràng)',
        description: 'Đồng bộ hóa danh bạ tìm bạn bè',
      },
      {
        name: 'android.permission.READ_SMS',
        shortName: 'READ_SMS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Không nên xin toàn quyền đọc SMS người dùng chỉ để lấy mã OTP',
        ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu',
        description: 'Đọc hòm thư tin nhắn SMS',
      },
      {
        name: 'android.permission.ACCESS_BACKGROUND_LOCATION',
        shortName: 'ACCESS_BACKGROUND_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Theo dõi vị trí ngầm 24/7 xâm phạm đời tư người dùng nghiêm trọng',
        ruleViolated: 'Quy tắc 1 & 3: Thiếu căn cứ hợp pháp và xâm phạm quyền riêng tư',
        description: 'Định vị ngầm chạy liên tục',
      },
      {
        name: 'android.permission.READ_MEDIA_IMAGES',
        shortName: 'READ_MEDIA_IMAGES',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Cho phép người dùng chọn ảnh tải lên bài viết',
        description: 'Đọc thư viện ảnh',
      },
      {
        name: 'android.permission.POST_NOTIFICATIONS',
        shortName: 'POST_NOTIFICATIONS',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Báo tin nhắn mới và thông báo hoạt động bạn bè',
        description: 'Gửi thông báo tin nhắn',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Kết nối máy chủ truyền dữ liệu chat',
        description: 'Kết nối mạng',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Quản lý trạng thái mạng',
        description: 'Kiểm tra trạng thái mạng',
      },
    ],
  },
  {
    appName: 'Beauty Filter Photo Editor',
    packageName: 'com.filter.beautycam.art',
    version: '4.0.1',
    fileSizeMb: 28.4,
    scanTime: '26/09/2026 - 08:22:04',
    appCategory: 'photo_editor',
    categoryNameVi: 'Chỉnh sửa ảnh / Camera (Photo Editor)',
    totalPermissions: 6,
    dangerousCount: 4,
    violationCount: 2,
    complianceScore: 42,
    complianceRating: 'RED',
    ratingLabel: 'VI PHẠM NGHIÊM TRỌNG (RED)',
    violationsSummary: [
      'App chỉnh sửa ảnh xin quyền đọc số điện thoại và trạng thái cuộc gọi (READ_PHONE_STATE)',
      'Thu thập tọa độ vị trí chính xác người dùng (ACCESS_FINE_LOCATION) không phục vụ tính năng lọc ảnh',
    ],
    recommendations: [
      'Loại bỏ quyền android.permission.READ_PHONE_STATE',
      'Loại bỏ quyền android.permission.ACCESS_FINE_LOCATION, nếu cần gắn geotag vào ảnh hãy hỏi xin riêng biệt',
    ],
    permissions: [
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Chụp ảnh trực tiếp với filter làm đẹp',
        description: 'Máy ảnh chụp hình',
      },
      {
        name: 'android.permission.READ_EXTERNAL_STORAGE',
        shortName: 'READ_EXTERNAL_STORAGE',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Mở ảnh từ album để chỉnh sửa',
        description: 'Đọc ảnh từ bộ nhớ',
      },
      {
        name: 'android.permission.READ_PHONE_STATE',
        shortName: 'READ_PHONE_STATE',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Ứng dụng lọc ảnh không có lý do chính đáng để đọc IMEI và số thuê bao!',
        ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu cá nhân',
        description: 'Đọc số điện thoại & IMEI máy',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Định vị người dùng khi đang áp dụng filter không có cơ sở pháp lý',
        ruleViolated: 'Quy tắc 2: Mục đích giới hạn',
        description: 'Lấy vị trí GPS người dùng',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Tải gói sticker và bộ lọc màu mới từ cloud',
        description: 'Kết nối mạng',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Rung nhẹ khi chụp xong ảnh',
        description: 'Rung máy',
      },
    ],
  },

  // Fix #8: Bổ sung 4 sample APK còn thiếu cho ecommerce, fitness, utility, gaming
  {
    appName: 'ShopVN Express',
    packageName: 'vn.shopvn.express.android',
    version: '5.1.0',
    fileSizeMb: 34.7,
    scanTime: '26/09/2026 - 14:30:00',
    appCategory: 'ecommerce',
    categoryNameVi: 'Mua sắm & Thương mại điện tử (E-Commerce)',
    totalPermissions: 7,
    dangerousCount: 3,
    violationCount: 1,
    complianceScore: 75,
    complianceRating: 'YELLOW',
    ratingLabel: 'CẢNH BÁO TUÂN THỦ (YELLOW)',
    violationsSummary: [
      'App mua sắm xin toàn quyền đọc tin nhắn SMS (READ_SMS) chỉ để lấy OTP — vi phạm nguyên tắc tối thiểu hóa dữ liệu',
    ],
    recommendations: [
      'Thay thế READ_SMS bằng SMS Retriever API của Google để nhận OTP không cần đọc toàn bộ hòm thư',
      'Đảm bảo chính sách bảo mật mô tả rõ mục đích thu thập vị trí (giao hàng) và yêu cầu sự đồng ý tường minh',
    ],
    permissions: [
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Kết nối máy chủ thương mại điện tử để tải sản phẩm và xử lý đơn hàng',
        description: 'Kết nối mạng Internet',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Kiểm tra kết nối trước khi thực hiện thanh toán',
        description: 'Kiểm tra trạng thái mạng',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Xác định địa chỉ giao hàng và tìm cửa hàng gần nhất',
        description: 'Định vị GPS để hỗ trợ giao hàng',
      },
      {
        name: 'android.permission.CAMERA',
        shortName: 'CAMERA',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Quét mã QR sản phẩm và chụp ảnh khi đánh giá đơn hàng',
        description: 'Máy ảnh quét mã QR',
      },
      {
        name: 'android.permission.POST_NOTIFICATIONS',
        shortName: 'POST_NOTIFICATIONS',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Thông báo trạng thái đơn hàng và khuyến mãi',
        description: 'Gửi thông báo đẩy',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Bình thường - Rung xúc giác khi xác nhận thanh toán',
        description: 'Rung phản hồi',
      },
      {
        name: 'android.permission.READ_SMS',
        shortName: 'READ_SMS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Đọc toàn bộ hòm thư SMS chỉ để lấy OTP là quá mức cần thiết, có thể lấy mã ngân hàng và tin nhắn riêng tư',
        ruleViolated: 'Quy tắc 3 (GDPR & Luật BV Dữ Liệu Cá Nhân 2025): Tối thiểu hóa dữ liệu (Data Minimization)',
        description: 'Đọc toàn bộ tin nhắn SMS kể cả OTP ngân hàng',
      },
    ],
  },
  {
    appName: 'FitTrack Sức Khỏe',
    packageName: 'com.fittrack.health.vn',
    version: '3.0.2',
    fileSizeMb: 18.5,
    scanTime: '26/09/2026 - 15:10:00',
    appCategory: 'fitness',
    categoryNameVi: 'Sức khỏe & Thể thao (Fitness / Health)',
    totalPermissions: 7,
    dangerousCount: 4,
    violationCount: 0,
    complianceScore: 100,
    complianceRating: 'GREEN',
    ratingLabel: 'TUÂN THỦ RẤT TỐT (GREEN)',
    violationsSummary: [],
    recommendations: [
      'Ứng dụng tuân thủ rất tốt nguyên tắc tối thiểu hóa dữ liệu — chỉ yêu cầu quyền phục vụ trực tiếp chức năng theo dõi sức khỏe.',
      'Nên bổ sung chính sách bảo mật rõ ràng về thời hạn lưu trữ dữ liệu sinh trắc học và quyền xóa của người dùng.',
    ],
    permissions: [
      {
        name: 'android.permission.ACTIVITY_RECOGNITION',
        shortName: 'ACTIVITY_RECOGNITION',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Nhận biết hoạt động đi bộ, chạy, đạp xe để đếm bước và tính calo',
        description: 'Nhận biết vận động thể chất',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Theo dõi lộ trình chạy bộ và tính khoảng cách chính xác bằng GPS',
        description: 'Định vị GPS theo dõi lộ trình',
      },
      {
        name: 'android.permission.ACCESS_COARSE_LOCATION',
        shortName: 'ACCESS_COARSE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Xác định khu vực địa lý để gợi ý tuyến đường phổ biến',
        description: 'Định vị khu vực qua mạng',
      },
      {
        name: 'android.permission.BODY_SENSORS',
        shortName: 'BODY_SENSORS',
        isDangerous: true,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Đọc nhịp tim từ cảm biến của đồng hồ thông minh kết nối',
        description: 'Đọc cảm biến nhịp tim',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Đồng bộ dữ liệu luyện tập lên cloud và tải kế hoạch tập',
        description: 'Kết nối mạng đồng bộ dữ liệu',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Chuyển sang chế độ offline khi mất mạng',
        description: 'Kiểm tra kết nối mạng',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Rung nhắc nhở khi đạt mốc bước chân hoặc hết giờ nghỉ',
        description: 'Rung nhắc nhở luyện tập',
      },
    ],
  },
  {
    appName: 'Smart Notes & Alarm',
    packageName: 'com.smartnotes.alarm.utility',
    version: '2.1.3',
    fileSizeMb: 8.2,
    scanTime: '26/09/2026 - 16:00:00',
    appCategory: 'utility',
    categoryNameVi: 'Tiện ích hệ thống (Utilities)',
    totalPermissions: 7,
    dangerousCount: 1,
    violationCount: 1,
    complianceScore: 75,
    complianceRating: 'YELLOW',
    ratingLabel: 'CẢNH BÁO TUÂN THỦ (YELLOW)',
    violationsSummary: [
      'App ghi chú và báo thức yêu cầu định vị GPS chính xác (ACCESS_FINE_LOCATION) — không có lý do chính đáng cho tiện ích này',
    ],
    recommendations: [
      'Loại bỏ quyền android.permission.ACCESS_FINE_LOCATION — chức năng ghi chú và báo thức không cần vị trí GPS',
      'Nếu muốn tính năng nhắc nhở theo địa điểm, hãy xin quyền chỉ khi người dùng chủ động bật tính năng đó',
    ],
    permissions: [
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Rung khi báo thức kích hoạt',
        description: 'Rung báo thức',
      },
      {
        name: 'android.permission.WAKE_LOCK',
        shortName: 'WAKE_LOCK',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Giữ màn hình sáng khi báo thức đang rung',
        description: 'Giữ màn hình hoạt động',
      },
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Đồng bộ ghi chú qua cloud',
        description: 'Kết nối mạng',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Kiểm tra kết nối trước khi đồng bộ',
        description: 'Kiểm tra trạng thái mạng',
      },
      {
        name: 'android.permission.RECEIVE_BOOT_COMPLETED',
        shortName: 'RECEIVE_BOOT_COMPLETED',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Khôi phục lịch báo thức sau khi thiết bị khởi động lại',
        description: 'Khởi động cùng hệ thống',
      },
      {
        name: 'android.permission.POST_NOTIFICATIONS',
        shortName: 'POST_NOTIFICATIONS',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Gửi thông báo nhắc nhở từ ghi chú',
        description: 'Thông báo nhắc nhở',
      },
      {
        name: 'android.permission.ACCESS_FINE_LOCATION',
        shortName: 'ACCESS_FINE_LOCATION',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Ứng dụng ghi chú và báo thức không có lý do hợp lệ để thu thập vị trí GPS chính xác của người dùng',
        ruleViolated: 'Quy tắc 2: Mục đích giới hạn (Purpose Limitation)',
        description: 'Định vị GPS chính xác người dùng',
      },
    ],
  },
  {
    appName: 'GameZone Racing 3D',
    packageName: 'com.gamezone.racing.mobile',
    version: '1.8.5',
    fileSizeMb: 87.3,
    scanTime: '26/09/2026 - 17:20:00',
    appCategory: 'gaming',
    categoryNameVi: 'Trò chơi di động (Gaming)',
    totalPermissions: 6,
    dangerousCount: 2,
    violationCount: 2,
    complianceScore: 42,
    complianceRating: 'RED',
    ratingLabel: 'VI PHẠM NGHIÊM TRỌNG (RED)',
    violationsSummary: [
      'Game đua xe xin đọc toàn bộ danh bạ điện thoại (READ_CONTACTS) — vi phạm nghiêm trọng, không liên quan đến gameplay',
      'Game xin quyền gửi tin nhắn SMS tự động (SEND_SMS) — có thể phát sinh cước phí trái phép cho người dùng',
    ],
    recommendations: [
      'Loại bỏ ngay quyền android.permission.READ_CONTACTS — game đua xe không có lý do nào cần danh bạ',
      'Loại bỏ ngay quyền android.permission.SEND_SMS — nếu cần mời bạn bè, hãy dùng Intent chia sẻ hệ thống thay vì gửi SMS trực tiếp',
      'Audit toàn bộ SDK bên thứ ba trong game — các vi phạm này thường do SDK quảng cáo nhúng vào',
    ],
    permissions: [
      {
        name: 'android.permission.INTERNET',
        shortName: 'INTERNET',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Tải màn chơi, bảng xếp hạng và kết nối multiplayer',
        description: 'Kết nối mạng game online',
      },
      {
        name: 'android.permission.ACCESS_NETWORK_STATE',
        shortName: 'ACCESS_NETWORK_STATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Kiểm tra kết nối trước khi vào màn multiplayer',
        description: 'Kiểm tra kết nối mạng',
      },
      {
        name: 'android.permission.VIBRATE',
        shortName: 'VIBRATE',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Rung lực phản hồi khi va chạm trong game',
        description: 'Haptic feedback va chạm',
      },
      {
        name: 'android.permission.WAKE_LOCK',
        shortName: 'WAKE_LOCK',
        isDangerous: false,
        isAllowedForCategory: true,
        status: 'valid',
        riskLevel: 'LOW',
        categoryExplanation: 'Hợp lý - Giữ màn hình sáng trong suốt phiên chơi',
        description: 'Giữ màn hình sáng khi chơi game',
      },
      {
        name: 'android.permission.READ_CONTACTS',
        shortName: 'READ_CONTACTS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm nghiêm trọng - Game đua xe không có chức năng nào cần đọc danh bạ. Đây là dấu hiệu của SDK quảng cáo hoặc spyware nhúng vào',
        ruleViolated: 'Quy tắc 3 (GDPR & Luật BV Dữ Liệu Cá Nhân 2025): Tối thiểu hóa dữ liệu (Data Minimization)',
        description: 'Đọc toàn bộ danh bạ điện thoại',
      },
      {
        name: 'android.permission.SEND_SMS',
        shortName: 'SEND_SMS',
        isDangerous: true,
        isAllowedForCategory: false,
        status: 'violation',
        riskLevel: 'HIGH',
        categoryExplanation: 'Vi phạm - Gửi SMS tự động không có sự đồng ý tường minh có thể phát sinh cước phí và phát tán spam cho danh bạ người dùng',
        ruleViolated: 'Quy tắc 1 & 3: Thiếu căn cứ pháp lý và xâm phạm quyền tự chủ của người dùng',
        description: 'Gửi tin nhắn SMS tự động',
      },
    ],
  },
];
