import { PolicySummaryResult } from '../types';

export interface PreloadedPolicyItem {
  id: string;
  name: string;
  url: string;
  rawText: string;
  analyzedResult: PolicySummaryResult;
}

export const PRELOADED_POLICIES: PreloadedPolicyItem[] = [
  {
    id: 'tiktok',
    name: 'TikTok Global Privacy Policy',
    url: 'https://tiktok.com/privacy-policy',
    rawText: `Chính sách Quyền riêng tư của TikTok: Chúng tôi thu thập thông tin hồ sơ của bạn gồm tên người dùng, mật khẩu, ngày sinh, địa chỉ email, số điện thoại. Chúng tôi tự động thu thập thông tin thiết bị (địa chỉ IP, nhà mạng di động, cài đặt múi giờ, số nhận dạng quảng cáo di động IDFA/GAID, kiểu thiết bị, hệ điều hành). Chúng tôi thu thập nội dung tin nhắn, video bạn đăng tải, lịch sử xem, thời lượng xem và nội dung bạn thích. Mục đích: Cung cấp, hỗ trợ, cá nhân hóa nội dung 'Dành cho bạn', hiển thị quảng cáo hướng đối tượng, cải thiện thuật toán và ngăn chặn gian lận. Chia sẻ dữ liệu: Chúng tôi chia sẻ dữ liệu của bạn với các nhà cung cấp dịch vụ bên thứ ba (lưu trữ đám mây, hỗ trợ kỹ thuật), các đối tác quảng cáo và đo lường (như Google, Meta, các mạng quảng cáo programmatic), các công ty cùng tập đoàn ByteDance Ltd. Thời gian lưu giữ: Chúng tôi lưu giữ thông tin của bạn chừng nào cần thiết để cung cấp dịch vụ hoặc tối đa 5 năm sau khi đóng tài khoản, hoặc lâu hơn theo yêu cầu điều tra pháp lý. Quyền của bạn: Bạn có quyền truy cập, chỉnh sửa, yêu cầu xóa dữ liệu của mình hoặc tải xuống bản sao dữ liệu trong phần Cài đặt ứng dụng. Một số thông tin quảng cáo hành vi vẫn có thể được phân phối theo danh mục chung.`,
    analyzedResult: {
      appName: 'TikTok',
      sourceUrl: 'https://tiktok.com/privacy-policy',
      analyzedAt: '26/09/2026 - 14:15:00',
      charCount: 1042,
      fivePoints: {
        collectedData: 'Tên, SĐT, Email, Location GPS, Device ID (IDFA/GAID), Lịch sử xem video, Nội dung tin nhắn và Danh bạ điện thoại.',
        purpose: 'Cung cấp dịch vụ, thuật toán gợi ý video cá nhân hóa, quảng cáo hướng đối tượng (Targeted Ads), phân tích hành vi và chống gian lận.',
        thirdPartySharing: 'Có chia sẻ cho: Google Ads, Meta/Facebook, các đối tác programmatic ads và các công ty liên kết trong tập đoàn ByteDance.',
        retentionPeriod: 'Tối đa 5 năm sau khi xóa tài khoản, hoặc lưu giữ lâu hơn không xác định nếu có yêu cầu điều tra pháp lý.',
        userRights: 'Có thể xuất dữ liệu cá nhân, yêu cầu xóa tài khoản, xem lịch sử và quản lý một phần quảng cáo trong phần Cài đặt.',
      },
      goldenRules: [
        {
          ruleNumber: 1,
          title: 'Hợp pháp & Đồng thuận (Consent)',
          criterion: 'Có sự đồng ý tự nguyện và tùy chọn từ chối quảng cáo?',
          passed: false,
          detail: 'Người dùng bắt buộc phải chấp nhận điều khoản quảng cáo hướng mục tiêu để được dùng app',
          legalReference: 'GDPR Điều 6 & 7, Nghị định 13/2023/NĐ-CP Điều 11',
        },
        {
          ruleNumber: 2,
          title: 'Mục đích giới hạn (Purpose Limitation)',
          criterion: 'Mục đích thu thập rõ ràng, không sử dụng ngoài phạm vi?',
          passed: true,
          detail: 'Mục đích vận hành nền tảng video và thuật toán đề xuất được nêu chi tiết',
          legalReference: 'GDPR Điều 5(1)(b), Nghị định 13/2023/NĐ-CP Điều 3',
        },
        {
          ruleNumber: 3,
          title: 'Tối thiểu hóa dữ liệu (Data Minimization)',
          criterion: 'Chỉ thu thập thông tin thực sự cần thiết?',
          passed: false,
          detail: 'Thu thập nhận dạng thiết bị IDFA, thói quen gõ phím và vị trí tương đối sâu hơn mức cần thiết',
          legalReference: 'GDPR Điều 5(1)(c), Luật BV Dữ Liệu Cá Nhân 2025',
        },
        {
          ruleNumber: 4,
          title: 'Tính minh bạch (Transparency)',
          criterion: 'Thông tin bên thứ ba và thời gian lưu trữ có cụ thể?',
          passed: false,
          detail: 'Mục chia sẻ đối tác quảng cáo còn chung chung, thời hạn "hoặc lâu hơn" thiếu mốc giới hạn',
          legalReference: 'GDPR Điều 12-14, Nghị định 13/2023/NĐ-CP Điều 13',
        },
        {
          ruleNumber: 5,
          title: 'Bảo mật & An toàn (Security & Integrity)',
          criterion: 'Có các biện pháp mã hóa và phòng ngừa rò rỉ dữ liệu?',
          passed: true,
          detail: 'Có đề cập hệ thống tường lửa, mã hóa TLS và bảo vệ dữ liệu đám mây',
          legalReference: 'GDPR Điều 32, Nghị định 13/2023/NĐ-CP Điều 26',
        },
      ],
      violations: [
        {
          title: 'Mục "Chia sẻ dữ liệu đối tác" còn mơ hồ',
          ruleViolated: 'Quy tắc 4: Tính minh bạch (Transparency)',
          legalBasis: 'GDPR Điều 13 & Nghị định 13/2023/NĐ-CP Điều 13',
          severity: 'MEDIUM',
          detail: 'Không liệt kê danh sách định danh cụ thể các mạng lưới quảng cáo và tổ chức đối tác nhận dữ liệu.',
        },
        {
          title: 'Thiếu cơ chế từ chối (Opt-out) quảng cáo hành vi triệt để',
          ruleViolated: 'Quy tắc 1: Hợp pháp & Đồng thuận tự nguyện',
          legalBasis: 'GDPR Điều 7(3) & Luật BV Dữ Liệu Cá Nhân 2025',
          severity: 'HIGH',
          detail: 'Người dùng không thể hoàn toàn tắt việc theo dõi hành vi xuyên nền tảng nếu muốn tiếp tục trải nghiệm.',
        },
        {
          title: 'Điều khoản thời hạn lưu giữ "lâu hơn nếu cần" thiếu mốc xác định',
          ruleViolated: 'Quy tắc 3: Giới hạn lưu trữ (Storage Limitation)',
          legalBasis: 'GDPR Điều 5(1)(e)',
          severity: 'LOW',
          detail: 'Cụm từ mở rộng không giới hạn tạo lỗ hổng lưu trữ dữ liệu cá nhân vô thời hạn.',
        },
      ],
      riskScore: 65,
      riskRating: 'MEDIUM',
      ratingLabel: 'CẢNH BÁO RỦI RO TRUNG BÌNH',
      recommendations: [
        'Cung cấp bảng phân loại danh sách các đối tác thứ ba nhận dữ liệu được cập nhật công khai định kỳ.',
        'Bổ sung nút gạt tắt hoàn toàn Personalized Ads trong giao diện mà không làm suy giảm chất lượng ứng dụng.',
        'Quy định thời hạn xóa dứt điểm dữ liệu nhật ký (Logs) tối đa 12 tháng.',
      ],
    },
  },
  {
    id: 'shopee',
    name: 'Shopee Vietnam Privacy Notice',
    url: 'https://shopee.vn/docs/privacy',
    rawText: `Chính sách Bảo mật Shopee: Chúng tôi thu thập dữ liệu cá nhân của người dùng bao gồm: Họ tên, địa chỉ nhận hàng, số điện thoại, email, thông tin tài khoản ngân hàng/ví điện tử liên kết, hình ảnh CCCD khi xác thực danh tính Người Bán. Khi sử dụng ứng dụng, chúng tôi ghi nhận địa chỉ IP, vị trí GPS khi chọn điểm giao nhận, thông tin giao dịch mua sắm và lịch sử chat với người bán. Mục đích sử dụng: Xử lý đơn hàng, điều phối giao vận thông qua các đơn vị bưu chính (SPX, GHTK, GHN), bảo đảm thanh toán và hoàn tiền, bảo vệ người tiêu dùng chống lừa đảo, đề xuất mã giảm giá phù hợp. Chia sẻ thông tin: Chúng tôi chia sẻ thông tin giao nhận (tên, SĐT, địa chỉ) cho người bán và tài xế vận chuyển; chia sẻ với các ngân hàng đối tác xử lý giao dịch; không bán dữ liệu cho bên thứ ba vì mục đích tiếp thị độc lập. Thời gian lưu trữ: Lưu trữ dữ liệu giao dịch trong 10 năm theo quy định của Luật Kế toán và Luật Thương mại điện tử Việt Nam. Quyền của chủ thể dữ liệu: Người dùng có quyền xem, chỉnh sửa thông tin giao hàng, hủy tài khoản bất cứ lúc nào qua Trung tâm trợ giúp của Shopee.`,
    analyzedResult: {
      appName: 'Shopee',
      sourceUrl: 'https://shopee.vn/docs/privacy',
      analyzedAt: '26/09/2026 - 15:00:20',
      charCount: 978,
      fivePoints: {
        collectedData: 'Họ tên, SĐT, Địa chỉ giao hàng, Lịch sử mua sắm, Vị trí GPS khi đặt hàng, và CCCD (đối với Nhà Bán Hàng).',
        purpose: 'Xử lý đơn đặt hàng, giao hàng chặng cuối, thanh toán/hoàn tiền trực tuyến và phòng chống gian lận thương mại.',
        thirdPartySharing: 'Chia sẻ có chọn lọc cho Đơn vị vận chuyển (SPX, GHTK), Người bán (để đóng gói) và Ngân hàng trung gian thanh toán.',
        retentionPeriod: 'Lưu trữ hồ sơ giao dịch 10 năm theo nghĩa vụ pháp lý của Luật Kế toán & Luật Thương mại Điện tử Việt Nam.',
        userRights: 'Quyền xem lại hóa đơn, sửa đổi địa chỉ, yêu cầu hủy tài khoản và rút lại đồng thuận marketing.',
      },
      goldenRules: [
        {
          ruleNumber: 1,
          title: 'Hợp pháp & Đồng thuận (Consent)',
          criterion: 'Có căn cứ hợp đồng mua bán và sự chấp thuận rõ ràng?',
          passed: true,
          detail: 'Thu thập thông tin gắn liền trực tiếp với thực hiện hợp đồng mua bán thương mại điện tử',
          legalReference: 'GDPR Điều 6(1)(b), Nghị định 13/2023/NĐ-CP Điều 17',
        },
        {
          ruleNumber: 2,
          title: 'Mục đích giới hạn (Purpose Limitation)',
          criterion: 'Mục đích xử lý đơn hàng và giao vận được quy định cụ thể?',
          passed: true,
          detail: 'Chỉ phục vụ giao nhận hàng hóa và thanh toán, cam kết không bán dữ liệu cho bên thứ ba',
          legalReference: 'GDPR Điều 5(1)(b), Luật BV Dữ Liệu Cá Nhân 2025',
        },
        {
          ruleNumber: 3,
          title: 'Tối thiểu hóa dữ liệu (Data Minimization)',
          criterion: 'Chỉ thu thập thông tin cần thiết cho việc vận chuyển và thanh toán?',
          passed: true,
          detail: 'Các trường thông tin địa chỉ, SĐT đều là bắt buộc đối với hoạt động bưu chính vận chuyển',
          legalReference: 'GDPR Điều 5(1)(c)',
        },
        {
          ruleNumber: 4,
          title: 'Tính minh bạch (Transparency)',
          criterion: 'Thời hạn lưu trữ và bên nhận dữ liệu được nêu rõ ràng?',
          passed: true,
          detail: 'Nêu căn cứ thời hạn 10 năm theo luật kế toán và danh mục bên nhận dữ liệu giao vận',
          legalReference: 'GDPR Điều 13, Nghị định 13/2023/NĐ-CP Điều 13',
        },
        {
          ruleNumber: 5,
          title: 'Bảo mật & An toàn (Security & Integrity)',
          criterion: 'Mã hóa thông tin thẻ thanh toán và chứng từ tài chính?',
          passed: true,
          detail: 'Đạt chứng nhận bảo mật PCI-DSS cho hệ thống thanh toán điện tử',
          legalReference: 'GDPR Điều 32, Nghị định 13/2023/NĐ-CP Điều 26',
        },
      ],
      violations: [],
      riskScore: 88,
      riskRating: 'LOW',
      ratingLabel: 'TUÂN THỦ RẤT TỐT (RỦI RO THẤP)',
      recommendations: [
        'Bổ sung tính năng ẩn số điện thoại người nhận (mặt số ảo) trên nhãn in bưu kiện khi giao hàng.',
        'Cho phép người dùng tự xóa các thẻ ngân hàng đã lưu trong 1 bước thuận tiện.',
      ],
    },
  },
  {
    id: 'flashlight_sketchy',
    name: 'Đèn Pin Siêu Sáng Pro Policy (App Giả Mạo / Độc Hại)',
    url: 'https://brighttorch.example.com/privacy',
    rawText: `Chính sách Bảo mật Ứng dụng Đèn Pin: Khi bạn cài đặt ứng dụng, chúng tôi tự động đọc danh bạ điện thoại, đọc toàn bộ tin nhắn SMS, ghi lại nhật ký cuộc gọi và theo dõi vị trí GPS thời gian thực. Chúng tôi cũng truy cập camera và thư viện hình ảnh của bạn. Mục đích: Chúng tôi sử dụng các thông tin này cho mọi mục đích kinh doanh hợp pháp, bao gồm việc nghiên cứu thị trường, phân phối quảng cáo và bán lại dữ liệu cho các đối tác dữ liệu quốc tế. Chia sẻ bên thứ ba: Chúng tôi có quyền chuyển nhượng hoặc bán lại danh bạ, số điện thoại và tin nhắn của bạn cho bất kỳ bên thứ ba nào mà không cần sự đồng ý bổ sung. Thời gian lưu trữ: Dữ liệu được lưu trữ vĩnh viễn trên máy chủ của chúng tôi. Quyền người dùng: Ứng dụng là miễn phí, do đó người dùng từ bỏ mọi quyền yêu cầu xóa hoặc chỉnh sửa dữ liệu đã gửi. Nếu không đồng ý, bạn chỉ có thể gỡ ứng dụng khỏi máy.`,
    analyzedResult: {
      appName: 'Đèn Pin Siêu Sáng Pro',
      sourceUrl: 'https://brighttorch.example.com/privacy',
      analyzedAt: '26/09/2026 - 16:20:10',
      charCount: 785,
      fivePoints: {
        collectedData: 'Đọc toàn bộ danh bạ, đọc nội dung tin nhắn SMS cá nhân, nhật ký cuộc gọi, vị trí GPS thời gian thực và ảnh trong thư viện.',
        purpose: 'Sử dụng cho "mọi mục đích kinh doanh không xác định", tiếp thị lại và thương mại hóa bán dữ liệu người dùng.',
        thirdPartySharing: 'Tự ý chuyển nhượng hoặc bán dữ liệu cá nhân cho các đơn vị trung gian quốc tế mà không cần hỏi lại người dùng.',
        retentionPeriod: 'Lưu trữ vĩnh viễn (Permanent) không bao giờ xóa trên máy chủ ngoại vi.',
        userRights: 'Tước đoạt toàn bộ quyền của người dùng: Không cho xóa, không cho chỉnh sửa, ép buộc chấp nhận.',
      },
      goldenRules: [
        {
          ruleNumber: 1,
          title: 'Hợp pháp & Đồng thuận (Consent)',
          criterion: 'Có consent tự nguyện và quyền rút lại sự đồng ý?',
          passed: false,
          detail: 'Tước đoạt quyền rút lại đồng thuận, ép buộc chấp nhận theo hình thức Take-it-or-leave-it',
          legalReference: 'GDPR Điều 7, Nghị định 13/2023/NĐ-CP Điều 11',
        },
        {
          ruleNumber: 2,
          title: 'Mục đích giới hạn (Purpose Limitation)',
          criterion: 'Mục đích thu thập có cụ thể và chính đáng?',
          passed: false,
          detail: 'Điều khoản "mọi mục đích kinh doanh" là vi phạm nghiêm trọng nguyên tắc xác định mục đích',
          legalReference: 'GDPR Điều 5(1)(b), Nghị định 13/2023/NĐ-CP Điều 3',
        },
        {
          ruleNumber: 3,
          title: 'Tối thiểu hóa dữ liệu (Data Minimization)',
          criterion: 'Chỉ thu thập dữ liệu cần thiết cho chức năng đèn pin?',
          passed: false,
          detail: 'Thu thập SMS, Danh bạ, Vị trí GPS hoàn toàn không phục vụ chức năng phát sáng đèn LED',
          legalReference: 'GDPR Điều 5(1)(c), Luật BV Dữ Liệu Cá Nhân 2025',
        },
        {
          ruleNumber: 4,
          title: 'Tính minh bạch (Transparency)',
          criterion: 'Minh bạch bên thứ ba và thời gian lưu giữ?',
          passed: false,
          detail: 'Bán dữ liệu không công bố danh tính bên mua, lưu trữ vĩnh viễn trái pháp luật',
          legalReference: 'GDPR Điều 13-14',
        },
        {
          ruleNumber: 5,
          title: 'Bảo mật & An toàn (Security & Integrity)',
          criterion: 'Có cam kết các tiêu chuẩn bảo mật dữ liệu?',
          passed: false,
          detail: 'Không có bất kỳ cam kết hay quy trình bảo mật thông tin nhạy cảm của người dùng',
          legalReference: 'GDPR Điều 32, Nghị định 13/2023/NĐ-CP Điều 26',
        },
      ],
      violations: [
        {
          title: 'Bán dữ liệu cá nhân không có sự đồng thuận riêng biệt',
          ruleViolated: 'Quy tắc 1 & Luật Bảo vệ dữ liệu cá nhân 2025',
          legalBasis: 'Nghị định 13/2023/NĐ-CP Điều 9 & Điều 21 (Hành vi bị nghiêm cấm)',
          severity: 'HIGH',
          detail: 'Hành vi mua bán dữ liệu cá nhân không có sự cho phép cụ thể của chủ thể là hành vi vi phạm pháp luật nghiêm trọng.',
        },
        {
          title: 'Vi phạm nguyên tắc Tối thiểu hóa dữ liệu nghiêm trọng',
          ruleViolated: 'Quy tắc 3: Tối thiểu hóa dữ liệu',
          legalBasis: 'GDPR Điều 5(1)(c)',
          severity: 'HIGH',
          detail: 'Ứng dụng tiện ích đèn pin đòi hỏi đọc toàn bộ tin nhắn SMS riêng tư và danh bạ bạn bè.',
        },
        {
          title: 'Tước đoạt quyền Xóa dữ liệu (Right to Erasure) của người dùng',
          ruleViolated: 'Quy tắc 1 & Quyền của chủ thể dữ liệu',
          legalBasis: 'GDPR Điều 17 (Right to be Forgotten) & Nghị định 13/2023 Điều 9',
          severity: 'HIGH',
          detail: 'Tuyên bố người dùng không được quyền yêu cầu xóa hay chỉnh sửa dữ liệu của mình.',
        },
        {
          title: 'Quy định thời gian lưu trữ vĩnh viễn',
          ruleViolated: 'Quy tắc 4: Giới hạn thời gian lưu trữ',
          legalBasis: 'GDPR Điều 5(1)(e)',
          severity: 'HIGH',
          detail: 'Dữ liệu cá nhân không được phép lưu trữ vĩnh viễn khi không còn mục đích sử dụng ban đầu.',
        },
      ],
      riskScore: 15,
      riskRating: 'HIGH',
      ratingLabel: 'VI PHẠM ĐẶC BIỆT NGUY HIỂM (RỦI RO RẤT CAO)',
      recommendations: [
        'NGƯỜI DÙNG CẦN GỠ BỎ ỨNG DỤNG NGAY LẬP TỨC để tránh rò rỉ mã OTP và danh bạ!',
        'Báo cáo ứng dụng lên Google Play Store vì hành vi thu thập dữ liệu độc hại (Spyware-like behavior).',
        'Thay đổi ngay mật khẩu các tài khoản trực tuyến quan trọng nếu đã cấp quyền đọc tin nhắn SMS.',
      ],
    },
  },
  {
    id: 'zalo',
    name: 'Zalo Privacy Policy (Bảo mật Tin cậy)',
    url: 'https://zalo.me/privacy',
    rawText: `Chính sách Bảo mật Zalo: Chúng tôi thu thập số điện thoại đăng ký, họ tên hiển thị, ngày sinh và ảnh đại diện do bạn cung cấp. Khi sử dụng tính năng đồng bộ bạn bè, Zalo sẽ hỏi xin quyền đọc danh bạ và chỉ băm (hash) số điện thoại để so khớp bạn bè, không lưu lại nội dung danh bạ thô. Tin nhắn đàm thoại cá nhân được bảo vệ bằng mã hóa đầu cuối (E2EE) trên thiết bị, máy chủ không thể đọc được nội dung tin nhắn. Chúng tôi không chia sẻ hoặc bán dữ liệu cá nhân cho bên thứ ba vì mục đích thương mại ngoài hệ sinh thái VNG. Dữ liệu tài khoản được lưu giữ trong suốt thời gian bạn duy trì tài khoản; khi bạn xóa tài khoản, toàn bộ dữ liệu hồ sơ sẽ được thanh lọc vĩnh viễn sau 30 ngày thời gian ân hạn. Bạn có toàn quyền xuất dữ liệu, thu hồi quyền truy cập danh bạ/camera trong Cài đặt quyền riêng tư bất kỳ lúc nào.`,
    analyzedResult: {
      appName: 'Zalo',
      sourceUrl: 'https://zalo.me/privacy',
      analyzedAt: '26/09/2026 - 17:10:00',
      charCount: 890,
      fivePoints: {
        collectedData: 'Số điện thoại đăng ký, tên hiển thị, ảnh đại diện; băm (hash) danh bạ điện thoại để tìm bạn bè.',
        purpose: 'Xác thực tài khoản, kết nối bạn bè, gửi tin nhắn đàm thoại thoại/video và đồng bộ thiết bị.',
        thirdPartySharing: 'Không bán hoặc chia sẻ thông tin cá nhân cho đối tác bên thứ ba bên ngoài dịch vụ.',
        retentionPeriod: 'Lưu trữ trong suốt thời gian sử dụng tài khoản; xóa triệt để sau 30 ngày kể từ khi bấm Xóa tài khoản.',
        userRights: 'Quyền xem lại dữ liệu, bật/tắt quyền danh bạ, quyền xóa tài khoản vĩnh viễn và mã hóa E2EE cho tin nhắn riêng tư.',
      },
      goldenRules: [
        {
          ruleNumber: 1,
          title: 'Hợp pháp & Đồng thuận (Consent)',
          criterion: 'Có consent minh bạch và cho phép thu hồi bất kỳ lúc nào?',
          passed: true,
          detail: 'Người dùng có thể chủ động tắt đồng bộ danh bạ trong cài đặt',
          legalReference: 'GDPR Điều 7, Nghị định 13/2023/NĐ-CP Điều 11',
        },
        {
          ruleNumber: 2,
          title: 'Mục đích giới hạn (Purpose Limitation)',
          criterion: 'Mục đích giới hạn trong liên lạc thoại và tin nhắn?',
          passed: true,
          detail: 'Rõ ràng, giới hạn trong phạm vi ứng dụng nhắn tin liên lạc',
          legalReference: 'GDPR Điều 5(1)(b)',
        },
        {
          ruleNumber: 3,
          title: 'Tối thiểu hóa dữ liệu (Data Minimization)',
          criterion: 'Áp dụng biện pháp mã hóa băm số điện thoại danh bạ?',
          passed: true,
          detail: 'Sử dụng kỹ thuật Hash danh bạ để không lưu trữ danh bạ thô của người dùng',
          legalReference: 'GDPR Điều 5(1)(c) & Điều 32',
        },
        {
          ruleNumber: 4,
          title: 'Tính minh bạch (Transparency)',
          criterion: 'Quy định rõ thời hạn xóa dữ liệu 30 ngày?',
          passed: true,
          detail: 'Chính sách nêu rõ thời hạn thanh lọc 30 ngày sau khi hủy tài khoản',
          legalReference: 'GDPR Điều 13, Nghị định 13/2023/NĐ-CP Điều 13',
        },
        {
          ruleNumber: 5,
          title: 'Bảo mật & An toàn (Security & Integrity)',
          criterion: 'Ứng dụng công nghệ mã hóa đầu cuối E2EE?',
          passed: true,
          detail: 'Triển khai mã hóa End-to-End Encryption cho các đoạn hội thoại',
          legalReference: 'GDPR Điều 32, Nghị định 13/2023/NĐ-CP Điều 26',
        },
      ],
      violations: [],
      riskScore: 92,
      riskRating: 'LOW',
      ratingLabel: 'TUÂN THỦ RẤT CAO (AN TOÀN)',
      recommendations: [
        'Tiếp tục duy trì tính năng mã hóa đầu cuối mặc định cho tất cả các cuộc trò chuyện nhóm lớn.',
        'Cung cấp thông báo khi có thiết bị lạ đăng nhập tài khoản từ địa điểm mới.',
      ],
    },
  },
];
